name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Stage 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Stage 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Stage 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Stage 4: Run linting
      - name: Lint code
        run: |
          pip install flake8
          flake8 src tests

      # Stage 5: Run tests
      - name: Run tests
        run: |
          pip install pytest
          pytest --junitxml=test-results/results.xml
